// Generates a unified sitemap.xml by scanning the assembled _site directory
const fs = require('fs');
const path = require('path');

const SITE = 'https://aimunger.com';
const SITE_DIR = path.join(__dirname, '_site');

// Collect all HTML pages from the built site
function collectPages(dir, base = '') {
  const urls = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.isDirectory()) {
      urls.push(...collectPages(path.join(dir, entry.name), `${base}/${entry.name}`));
    } else if (entry.name === 'index.html') {
      urls.push(`${base}/`);
    }
  }
  return urls;
}

// Check for Astro-generated sitemap and extract URLs from it
function extractAstroSitemapUrls() {
  const urls = [];
  const lettersDir = path.join(SITE_DIR, 'letters');

  // Look for sitemap XML files generated by @astrojs/sitemap
  const sitemapFiles = ['sitemap-0.xml', 'sitemap.xml'].map(f => path.join(lettersDir, f));
  for (const file of sitemapFiles) {
    if (fs.existsSync(file)) {
      const content = fs.readFileSync(file, 'utf-8');
      const locRegex = /<loc>(.*?)<\/loc>/g;
      let match;
      while ((match = locRegex.exec(content)) !== null) {
        urls.push(match[1]);
      }
    }
  }
  return urls;
}

const today = new Date().toISOString().split('T')[0];

// Start with Astro sitemap URLs if available (they have correct site/base)
const astroUrls = extractAstroSitemapUrls();

// Fallback: scan _site directory for all index.html files
const scannedPages = collectPages(SITE_DIR);

// Merge: use Astro URLs + any pages not already covered
const allUrls = new Set(astroUrls);
for (const page of scannedPages) {
  allUrls.add(`${SITE}${page}`);
}

// Assign priorities and changefreq
function getPriority(url) {
  if (url === `${SITE}/`) return '1.0';
  if (url.endsWith('/letters/') || url.endsWith('/llm-reader/')) return '0.8';
  if (url.includes('/company/') || url.includes('/all-companies') || url.includes('/all-years')) return '0.7';
  if (url.includes('/letter/')) return '0.6';
  if (url.includes('/year/')) return '0.5';
  return '0.5';
}

function getChangefreq(url) {
  if (url === `${SITE}/`) return 'weekly';
  if (url.endsWith('/llm-reader/')) return 'daily';
  if (url.endsWith('/letters/')) return 'weekly';
  if (url.includes('/company/') || url.includes('/letter/')) return 'monthly';
  return 'monthly';
}

// Sort URLs for consistent output
const sortedUrls = [...allUrls].sort();

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${sortedUrls.map(url => `  <url>
    <loc>${url}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>${getChangefreq(url)}</changefreq>
    <priority>${getPriority(url)}</priority>
  </url>`).join('\n')}
</urlset>
`;

const outPath = path.join(SITE_DIR, 'sitemap.xml');
fs.writeFileSync(outPath, xml);
console.log(`Generated sitemap.xml with ${sortedUrls.length} URLs`);

// Clean up Astro's sitemap files from the letters subdirectory to avoid duplicates
for (const f of ['sitemap-0.xml', 'sitemap.xml', 'sitemap-index.xml']) {
  const p = path.join(SITE_DIR, 'letters', f);
  if (fs.existsSync(p)) fs.unlinkSync(p);
}
