// Generates a unified sitemap.xml by scanning the assembled _site directory
const fs = require('fs');
const path = require('path');
const { parseSimpleMeta, resolveGitDate, resolvePublishDate, splitFrontmatter } = require('./site-md-utils');

const SITE = 'https://aimunger.com';
const SITE_DIR = path.join(__dirname, '_site');
const BLOG_SOURCE_DIR = path.join(__dirname, 'blog');

// Map blog URLs to their publish dates so lastmod reflects real content age
// instead of the build date.
function buildLastmodMap() {
  const map = new Map();
  if (!fs.existsSync(BLOG_SOURCE_DIR)) return map;
  for (const file of fs.readdirSync(BLOG_SOURCE_DIR)) {
    if (!file.endsWith('.md')) continue;
    const filePath = path.join(BLOG_SOURCE_DIR, file);
    const raw = fs.readFileSync(filePath, 'utf-8');
    const meta = parseSimpleMeta(splitFrontmatter(raw).frontmatter);
    const slug = meta.slug || file.replace(/\.md$/, '');
    // Archival posts carry the original document's historical date in
    // frontmatter; lastmod must reflect when the page actually changed.
    const lastmod = resolveGitDate(filePath) || resolvePublishDate(filePath, meta.date);
    if (lastmod) map.set(`${SITE}/blog/${slug}/`, lastmod);
  }
  return map;
}

// Collect all HTML pages from the built site
// A page carrying a noindex robots directive must not appear in the sitemap;
// listing a noindexed URL triggers a "Submitted URL marked noindex" error in
// Search Console.
function isNoindex(filePath) {
  const html = fs.readFileSync(filePath, 'utf-8');
  return /<meta[^>]+name=["']robots["'][^>]*content=["'][^"']*noindex/i.test(html);
}

function collectPages(dir, base = '') {
  const urls = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.isDirectory()) {
      urls.push(...collectPages(path.join(dir, entry.name), `${base}/${entry.name}`));
    } else if (entry.name === 'index.html') {
      if (!isNoindex(path.join(dir, entry.name))) urls.push(`${base}/`);
    } else if (entry.name.endsWith('.html')) {
      if (!isNoindex(path.join(dir, entry.name))) urls.push(`${base}/${entry.name}`);
    }
  }
  return urls;
}

// Check for Astro-generated sitemap and extract URLs from it
function extractAstroSitemapUrls() {
  const urls = [];
  const lettersDir = path.join(SITE_DIR, 'letters');

  // Look for sitemap XML files generated by @astrojs/sitemap
  const sitemapFiles = ['sitemap-0.xml', 'sitemap.xml'].map(f => path.join(lettersDir, f));
  for (const file of sitemapFiles) {
    if (fs.existsSync(file)) {
      const content = fs.readFileSync(file, 'utf-8');
      const locRegex = /<loc>(.*?)<\/loc>/g;
      let match;
      while ((match = locRegex.exec(content)) !== null) {
        urls.push(match[1]);
      }
    }
  }
  return urls;
}

// Resolve a real last-modified date for a URL, or null to omit <lastmod>.
// A build-date fallback would stamp the whole site as "modified today" on
// every deploy, which teaches crawlers to distrust the field entirely —
// omitting is better than lying.
const MDA_CONTENT_DIR = path.join(__dirname, 'management-discussion-analysis', 'src', 'content', 'mda');
// The letters repo is checked out at CI with full history (fetch-depth: 0
// in deploy.yml) so its content files carry real git dates.
const LETTERS_CONTENT_DIR = path.join(__dirname, '_build', 'letters', 'src', 'content', 'letters');

function latestGitDate(dir) {
  if (!fs.existsSync(dir)) return null;
  const dates = fs.readdirSync(dir)
    .filter(f => f.endsWith('.md'))
    .map(f => resolveGitDate(path.join(dir, f)))
    .filter(Boolean);
  return dates.length ? dates.sort().pop() : null;
}

function resolveLastmod(url, lastmodMap) {
  if (lastmodMap.has(url)) return lastmodMap.get(url);
  const rel = url.slice(SITE.length);

  // MD&A pages are built from committed content files
  const mdaReport = rel.match(/^\/management-discussion-analysis\/report\/([^/]+)\/([^/]+)\/$/);
  if (mdaReport) return resolveGitDate(path.join(MDA_CONTENT_DIR, mdaReport[1], `${mdaReport[2]}.md`));
  const mdaCompany = rel.match(/^\/management-discussion-analysis\/company\/([^/]+)\/$/);
  if (mdaCompany) return latestGitDate(path.join(MDA_CONTENT_DIR, mdaCompany[1]));

  // Letters pages are built from the letters repo's content markdown
  const letter = rel.match(/^\/letters\/letter\/([^/]+)\/([^/]+)\/$/);
  if (letter) return resolveGitDate(path.join(LETTERS_CONTENT_DIR, letter[1], `${letter[2]}.md`));
  const lettersCompany = rel.match(/^\/letters\/company\/([^/]+)\/$/);
  if (lettersCompany) return latestGitDate(path.join(LETTERS_CONTENT_DIR, lettersCompany[1]));
  const lettersYear = rel.match(/^\/letters\/year\/([^/]+)\/$/);
  if (lettersYear && fs.existsSync(LETTERS_CONTENT_DIR)) {
    const dates = fs.readdirSync(LETTERS_CONTENT_DIR)
      .map(company => path.join(LETTERS_CONTENT_DIR, company, `${lettersYear[1]}.md`))
      .filter(f => fs.existsSync(f))
      .map(f => resolveGitDate(f))
      .filter(Boolean);
    if (dates.length) return dates.sort().pop();
  }

  // Committed page files: repo root (resources, data, static pages), then
  // the committed _site copy (wiki pages live only there). CI-built pages
  // with no committed counterpart (letters) resolve to null.
  const relFile = rel.endsWith('/') ? `${rel}index.html` : rel;
  for (const base of [__dirname, SITE_DIR]) {
    const candidate = path.join(base, `.${relFile}`);
    if (fs.existsSync(candidate)) {
      const date = resolveGitDate(candidate);
      if (date) return date;
    }
  }
  return null;
}

// Start with Astro sitemap URLs if available (they have correct site/base)
const astroUrls = extractAstroSitemapUrls();

// Fallback: scan _site directory for all index.html files
const scannedPages = collectPages(SITE_DIR);

// Merge: use Astro URLs + any pages not already covered
const allUrls = new Set(astroUrls);
for (const page of scannedPages) {
  allUrls.add(`${SITE}${page}`);
}

// Assign priorities and changefreq
function getPriority(url) {
  if (url === `${SITE}/`) return '1.0';
  if (url.endsWith('/blog/')) return '0.9';
  if (url.endsWith('/letters/') || url.endsWith('/management-discussion-analysis/')) return '0.8';
  if (url.includes('/blog/') && url !== `${SITE}/blog/`) return '0.7';
  if (url.includes('/company/') || url.includes('/all-companies') || url.includes('/all-years')) return '0.7';
  if (url.includes('/letter/') || url.includes('/report/')) return '0.6';
  if (url.includes('/year/')) return '0.5';
  return '0.5';
}

function getChangefreq(url) {
  if (url === `${SITE}/`) return 'weekly';
  if (url.includes('/blog/')) return 'weekly';
  if (url.endsWith('/letters/') || url.endsWith('/management-discussion-analysis/')) return 'weekly';
  if (url.includes('/company/') || url.includes('/letter/') || url.includes('/report/')) return 'monthly';
  return 'monthly';
}

// Sort URLs for consistent output
const sortedUrls = [...allUrls].sort();
const lastmodMap = buildLastmodMap();

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${sortedUrls.map(url => {
  const lastmod = resolveLastmod(url, lastmodMap);
  return `  <url>
    <loc>${url}</loc>${lastmod ? `
    <lastmod>${lastmod}</lastmod>` : ''}
    <changefreq>${getChangefreq(url)}</changefreq>
    <priority>${getPriority(url)}</priority>
  </url>`;
}).join('\n')}
</urlset>
`;

const outPath = path.join(SITE_DIR, 'sitemap.xml');
fs.writeFileSync(outPath, xml);
console.log(`Generated sitemap.xml with ${sortedUrls.length} URLs`);

// Clean up Astro's sitemap files from the letters subdirectory to avoid duplicates
for (const f of ['sitemap-0.xml', 'sitemap.xml', 'sitemap-index.xml']) {
  const p = path.join(SITE_DIR, 'letters', f);
  if (fs.existsSync(p)) fs.unlinkSync(p);
}
